# Generated by Django 5.2.6 on 2025-09-15 07:04

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
